### ISSUE TITLE
Docker modem raises : "a disk usage operation is already running" 

### ISSUE THREAD

**Issue by jeantil** [apocas/docker-modem#112]
Hi, 
while it doesn't prevent my test suite from running, I keep getting these errors in the console for which docker-modem seems to be the root cause: 

```
  console.error node_modules/jest-jasmine2/build/jasmine/Env.js:289
    Unhandled error

  console.error node_modules/jest-jasmine2/build/jasmine/Env.js:290
    Error: (HTTP code 500) server error - a disk usage operation is already running 
        at /home/jean/dev/startups/yupwego/src/yupwego/node_modules/docker-modem/lib/modem.js:257:17
        at getCause (/home/jean/dev/startups/yupwego/src/yupwego/node_modules/docker-modem/lib/modem.js:287:7)
        at Modem.Object.<anonymous>.Modem.buildPayload (/home/jean/dev/startups/yupwego/src/yupwego/node_modules/docker-modem/lib/modem.js:256:5)
        at IncomingMessage.<anonymous> (/home/jean/dev/startups/yupwego/src/yupwego/node_modules/docker-modem/lib/modem.js:232:14)
        at IncomingMessage.emit (events.js:187:15)
        at endReadableNT (_stream_readable.js:1094:12)
        at process._tickCallback (internal/process/next_tick.js:63:19)
``` 

`docker version` reports 
```
 docker version                                                                                                                                                                          ±[●●][master]
Client:
 Version:           19.03.3-ce
 API version:       1.40
 Go version:        go1.13.1
 Git commit:        a872fc2f86
 Built:             Wed Oct  9 02:28:51 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.3-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.1
  Git commit:       a872fc2f86
  Built:            Wed Oct  9 02:28:23 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.0.m
  GitCommit:        d50db0a42053864a270f648048f9a8b4f24eced3.m
 runc:
  Version:          1.0.0-rc9
  GitCommit:        d736ef14f0288d6993a1845745d6756cfc9ddd5a
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
`uname -srv` reports : 
```
Linux 5.3.6-1-MANJARO #1 SMP PREEMPT Sat Oct 12 09:30:05 UTC 2019
```
using docker-modem "version": "1.0.9"
which is pulled by testcontainers:   "version": "2.1.0"
in my project.

**Comment by ehossack** [comment]
I have the same issue, but if I switch to testcontainers version 2.0.0 the error goes away. This could be related to their library (e.g. the space check here: https://github.com/testcontainers/testcontainers-node/commit/4ba9d50ba0465087a3997fdbd79bc473bec3e10c)
