### ISSUE TITLE
incompatibility on Bun.js

### ISSUE THREAD

**Issue by huanent** [apocas/docker-modem#158]
docker-modem work in node, but run in Bun.js throw exception

[Bun.js](https://github.com/oven-sh/bun) getting more and more popular, and it would be great to support that.

```
338 | Modem.prototype.buildPayload = function (err, isStream, statusCodes, openStdin, req, res, json, cb) {
339 |   if (err) return cb(err, null);
340 | 
341 |   if (statusCodes[res.statusCode] !== true) {
342 |     getCause(isStream, res, json, function (err, cause) {
343 |       var msg = new Error(
                    ^
error: (HTTP code 302) unexpected -  
      at /Users/huanent/workspaces/temp/bun-test/node_modules/docker-modem/lib/modem.js:343:16
      at getCause (/Users/huanent/workspaces/temp/bun-test/node_modules/docker-modem/lib/modem.js:373:6)
      at /Users/huanent/workspaces/temp/bun-test/node_modules/docker-modem/lib/modem.js:342:4
      at /Users/huanent/workspaces/temp/bun-test/node_modules/docker-modem/lib/modem.js:310:10
      at endReadableNT (node:stream:2387:52)
      at processTicksAndRejections (:55:76)
```

**Comment by apocas** [comment]
Bun is supported and working :)

https://github.com/apocas/dockerode/actions/runs/6303551584/job/17113027357

Best regards,

**Comment by apocas** [comment]
https://github.com/apocas/docker-modem/actions/runs/6303626121/job/17113272538
